<?php

namespace Database\Seeders;

use App\Models\UserManagement\User;
use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $users = 
        [
            [
                'id'             => 1,
                'kepegawaian_id' => 1,
                'email'          => 'admin@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 2,
                'kepegawaian_id' => 2,
                'email'          => 'inspektur@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 3,
                'kepegawaian_id' => 3,
                'email'          => 'irbanwil1@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 4,
                'kepegawaian_id' => 4,
                'email'          => 'irbanwil2@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 5,
                'kepegawaian_id' => 5,
                'email'          => 'irbanwil3@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 6,
                'kepegawaian_id' => 6,
                'email'          => 'irbanwil4@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 7,
                'kepegawaian_id' => 7,
                'email'          => 'pptk@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 8,
                'kepegawaian_id' => 8,
                'email'          => 'pegawaiwil1@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 9,
                'kepegawaian_id' => 9,
                'email'          => 'pegawaiwil1b@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 10,
                'kepegawaian_id' => 10,
                'email'          => 'pegawaiwil1c@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 11,
                'kepegawaian_id' => 11,
                'email'          => 'pegawaiwil1d@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 12,
                'kepegawaian_id' => 12,
                'email'          => 'pegawaiwil1e@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 13,
                'kepegawaian_id' => 13,
                'email'          => 'pegawaiwil1f@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 14,
                'kepegawaian_id' => 14,
                'email'          => 'pegawaiwil2@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            
            [
                'id'             => 15,
                'kepegawaian_id' => 15,
                'email'          => 'pegawaiwil2b@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 16,
                'kepegawaian_id' => 16,
                'email'          => 'pegawaiwil2c@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 17,
                'kepegawaian_id' => 17,
                'email'          => 'pegawaiwil2d@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 18,
                'kepegawaian_id' => 18,
                'email'          => 'pegawaiwil2e@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 19,
                'kepegawaian_id' => 19,
                'email'          => 'pegawaiwil2f@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 20,
                'kepegawaian_id' => 20,
                'email'          => 'pegawaiwil3@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 21,
                'kepegawaian_id' => 21,
                'email'          => 'pegawaiwil3b@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 22,
                'kepegawaian_id' => 22,
                'email'          => 'pegawaiwil3c@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 23,
                'kepegawaian_id' => 23,
                'email'          => 'pegawaiwil3d@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 24,
                'kepegawaian_id' => 24,
                'email'          => 'pegawaiwil3e@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 25,
                'kepegawaian_id' => 25,
                'email'          => 'pegawaiwil3f@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 26,
                'kepegawaian_id' => 26,
                'email'          => 'pegawaiwil4@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 27,
                'kepegawaian_id' => 27,
                'email'          => 'pegawaiwil4b@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 28,
                'kepegawaian_id' => 28,
                'email'          => 'pegawaiwil4c@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 29,
                'kepegawaian_id' => 29,
                'email'          => 'pegawaiwil4d@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 30,
                'kepegawaian_id' => 30,
                'email'          => 'pegawaiwil4e@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 31,
                'kepegawaian_id' => 31,
                'email'          => 'pegawaiwil4f@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 32,
                'kepegawaian_id' => 32,
                'email'          => 'gubernur@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 33,
                'kepegawaian_id' => 33,
                'email'          => 'wakilgubernur@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 34,
                'kepegawaian_id' => 34,
                'email'          => 'sahat@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 35,
                'kepegawaian_id' => 35,
                'email'          => 'rika@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 36,
                'kepegawaian_id' => 36,
                'email'          => 'iwan@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
            [
                'id'             => 37,
                'kepegawaian_id' => 37,
                'email'          => 'wayanhari@gmail.com',
                'password'       => '$2y$10$imU.Hdz7VauIT3LIMCMbsOXvaaTQg6luVqkhfkBcsUd.SJW2XSRKO',
                'remember_token' => null,
                'created_at'     => '2019-04-15 19:13:32',
                'updated_at'     => '2019-04-15 19:13:32',
                'deleted_at'     => null,
            ],
        ];
        User::insert($users);
    }
}
